### ISSUE TITLE
Compilation issues with dmd v2.068.0

### ISSUE THREAD

**Issue by SonicFreak94** [JakobOvrum/Dirk#14]
Several errors occur while building in dmd v2.068.0 (on Windows) in loader/loader.d and ssl/openssl.d. Log [here](https://gist.github.com/SonicFreak94/f3b9ec76e085edd2bf7d).

**Comment by jamierocks** [comment]
This is also happening on OSX.
Log [here](https://gist.github.com/jamierocks/1170abad45b0a4a2ee7c)
